# Generated by Django 5.2 on 2025-05-07 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('index', models.CharField(max_length=10)),
                ('statement', models.TextField()),
                ('input_spec', models.TextField()),
                ('output_spec', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
                ('constraints', models.TextField(blank=True, null=True)),
                ('time_limit_ms', models.IntegerField()),
                ('memory_limit_mb', models.IntegerField()),
                ('difficulty_origin', models.IntegerField()),
                ('examples', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='contests.contest')),
                ('topics', models.ManyToManyField(blank=True, related_name='problems', to='topics.topic')),
            ],
        ),
    ]
