# Generated by Django 5.2 on 2025-04-28 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('index', models.CharField(max_length=10)),
                ('statement', models.TextField()),
                ('input_spec', models.TextField()),
                ('output_spec', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
                ('constraints', models.TextField(blank=True, null=True)),
                ('time_limit_ms', models.IntegerField()),
                ('memory_limit_mb', models.IntegerField()),
                ('difficulty_origin', models.IntegerField()),
                ('difficulty_source', models.CharField(max_length=50)),
                ('examples', models.JSONField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='contest.contest')),
            ],
        ),
    ]
