# Generated by Django 5.2 on 2025-05-01 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_topic_contest_created_at_contest_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('category', models.CharField(choices=[('sample', 'Sample'), ('handmade', 'Handmade'), ('random', 'Random'), ('extreme', 'Extreme'), ('custom', 'Custom')], default='handmade', max_length=10)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='contest.problem')),
            ],
        ),
    ]
