# Generated by Django 5.2 on 2025-05-01 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_testcase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='division',
            field=models.CharField(choices=[('Div1', 'Division 1'), ('Div2', 'Division 2'), ('Div3', 'Division 3'), ('Div4', 'Division 4'), ('Open', 'Open for All')], default='Open', max_length=10),
        ),
        migrations.AddField(
            model_name='contest',
            name='rated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty_source',
            field=models.CharField(choices=[('codeforces', 'Codeforces'), ('zacode', 'ZaCode'), ('other', 'Other')], default='zacode', max_length=50),
        ),
        migrations.CreateModel(
            name='ContestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('rating_change', models.FloatField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contest.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'contest')},
            },
        ),
    ]
