# Generated by Django 5.2 on 2025-05-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_contest_division_contest_rated_contest_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterModelTable(
            name='contest',
            table='contest',
        ),
    ]
