# Generated by Django 5.2 on 2025-05-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_contest_duration_minutes_alter_contest_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='difficulty_source',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
    ]
